runtime: python38 

instance_class: F2

env_variables:
  # this will be publicly available on GitHub and may be useful for a production URL, for instance. 
  MY_VAR: "my value"
  # this will be passed to your application's environment by GitHub, if the variable is set there.
  DB_PASSWORD: ${{ secrets.PRODUCTION_DATABASE_PASSWORD }}

handlers:
- url: /static
  static_dir: great_project/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto